# Generated by Django 5.2.5 on 2025-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_book_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rental_duration_days',
            field=models.PositiveSmallIntegerField(default=14),
        ),
    ]
