# Generated by Django 5.2.5 on 2025-08-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_order_is_confirmed_order_rental_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='borrower_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='borrower_reference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
